#!/usr/bin/env python

# Imports the Library class that is written in Library.py,
# which is inside the directory called library
#from library.Library import Library

# Imports the all the user defined exceptions in CLI_Audio_Exception.py,
# which is inside the directory called front
from front.CLI_Audio_Exception import *
from library.Library import Library
from front.FrontEnd import FrontEnd
from player.Player import Player
from curses import wrapper

def main():
    player = Player()
    library = Library()
    # try and except block
    try:
        front_end = FrontEnd(player, library)
    except CLI_Audio_File_Exception as err:
#        err = CLI_Audio_File_Exception()
        err.error()
    except CLI_Audio_Screen_Size_Exception as err:
#        err = CLI_Audio_Screen_Size_Exception()
        err.error()


if __name__ == "__main__":
    main()
